# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

## aliases
alias vi="vim"

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export GOPATH=$HOME/work
export PATH=$PATH:$HOME/work/bin/:$GOROOT/bin

export EDITOR=/usr/local/bin/vim


